---

  - name: FreePBX | Download
    unarchive:
      src: 'http://mirror.freepbx.org/modules/packages/freepbx/freepbx-13.0-latest.tgz'
      dest: '/usr/src/'
      copy: no

  - name: FreePBX | Install
    command: ' {{ item }}'
    args:
      chdir: '/usr/src/freepbx'
    with_items:
      - ./start_asterisk start
      - ./install -n
    notify:
      - restart apache2
      - start freepbx
    ignore_errors: yes

  - name: Reload FreePBX
    shell: fwconsole restart
